project_id = "cnjznmbgxprsrovmdywe"

[functions.product-lookup]
verify_jwt = false

[functions.firecrawl-proxy]
verify_jwt = false

[functions.send-individual-reminder]
verify_jwt = false

[functions.check-ready-items]
verify_jwt = false

[functions.send-push-notifications]
verify_jwt = false
